### ISSUE TITLE
Need for a contribution.md file 

### ISSUE THREAD

**Issue by deveshio** [shelcia/api-docucraft#5]
As your projects don't contain the contribution.md file 
it is getting difficult to get an understanding 
I know the 
steps are provided in readMe.md file 
but it is still better to have a contribution. md file instead of putting the steps in the readme. MD

ps: I am participating from codePeak please put label on this

**Comment by deveshio** [comment]
I'd like to solve this issue

**Comment by deveshio** [comment]
please provide me all the data what should I put in your contribution.md file 
1. how to setup your project 
2. what must be keep in consideration while contributing in your project
3. do's and don't do's 
etc

**Comment by shelcia** [comment]
2 and 3 can be general, 1: for client folder, it is react vite app, add instructions accordingly, server app -> nodejs

**Comment by praptisharma28** [comment]
Assign me, I am working on it. @shelcia

**Comment by praptisharma28** [comment]
@shelcia , I did a PR #8 , you can have a look!
